"use strict";
class Cafe extends Phaser.Scene{
 constructor(){super("cafe")}
 create(){scene=this;this.drawCafe()}
 drawCafe(){this.children.removeAll();var W=this.scale.width,H=this.scale.height,sx=W/360,sy=H/440;this.add.rectangle(W/2,H/2,W-20*sx,H-18*sy,0x1c1625).setStrokeStyle(3*sx,0x5b506c);for(var y=58;y<390;y+=18)for(var x=18;x<345;x+=18)if(((x+y)/18)%2<1)this.add.rectangle(x*sx,y*sy,18*sx,18*sy,0x201929,.55);this.add.rectangle(W/2,35*sy,W-30*sx,32*sy,0x342743).setStrokeStyle(2*sx,bossToday()?0xff6f80:0x6f6082);this.add.text(22*sx,25*sy,(bossToday()?"!! ":"")+(s.lang==="zh"?"夜班网吧":"NIGHT CAFE"),{fontFamily:"monospace",fontSize:(11*sx)+"px",color:bossToday()?"#ff8795":"#ffd25d"}).setResolution(2);this.add.text(332*sx,26*sy,"D"+s.day,{fontFamily:"monospace",fontSize:(9*sx)+"px",color:"#a79caf"}).setOrigin(1,0).setResolution(2);for(var i=0;i<12;i++)this.drawSeat(i,sx,sy);this.drawQueue(sx,sy);this.add.rectangle(180*sx,406*sy,220*sx,27*sy,0x5a3d29).setStrokeStyle(2*sx,0xa37542);this.add.text(154*sx,400*sy,s.lang==="zh"?"前台":"DESK",{fontFamily:"monospace",fontSize:(8*sx)+"px",color:"#fae7be"}).setResolution(2)}
 drawSeat(i,sx,sy){var col=i%3,row=Math.floor(i/3),x=(72+col*108)*sx,y=(103+row*62)*sy,q=s.seats[i],sel=s.selected===i;var box=this.add.rectangle(x,y,88*sx,49*sy,q?0x2a2c38:0x17131e,.97).setStrokeStyle((sel?3:2)*sx,sel?0xffd25d:(q?0x687080:0x3d3549));box.setInteractive({useHandCursor:true}).on("pointerdown",function(){s.selected=i;shopMode=null;save();render()});this.add.text(x-39*sx,y-21*sy,String(i+1),{fontFamily:"monospace",fontSize:(7*sx)+"px",color:"#81768f"}).setResolution(2);if(!q){this.add.text(x,y-3*sy,"+",{fontFamily:"monospace",fontSize:(18*sx)+"px",color:"#6c6279"}).setOrigin(.5).setResolution(2);return}var p=q.pc?pcBy(q.pc):null;this.add.rectangle(x,y-7*sy,30*sx,19*sy,p?p.color:0x4b4654).setStrokeStyle(2*sx,0xb9b1c8);this.add.rectangle(x,y+10*sy,26*sx,7*sy,0x6e4b34);if(p){var cw=Math.max(0,34*(q.condition/100))*sx;this.add.rectangle((x-17*sx)+cw/2,y+20*sy,cw,3*sy,q.condition<25?0xff7185:0x73d8aa);this.add.text(x+19*sx,y-13*sy,"T"+p.tier,{fontFamily:"monospace",fontSize:(6*sx)+"px",color:"#c6bdd1"}).setResolution(2)}if(q.busy){var type=q.customer||"student",c=customers[type];this.add.circle(x-29*sx,y+5*sy,7*sx,c.color);this.add.rectangle(x-29*sx,y+17*sy,11*sx,11*sy,c.color).setAlpha(.8)}}
 drawQueue(sx,sy){this.add.text(20*sx,359*sy,s.lang==="zh"?"队列":"QUEUE",{fontFamily:"monospace",fontSize:(7*sx)+"px",color:"#8e839b"}).setResolution(2);for(var i=0;i<Math.min(5,s.queue.length);i++){var it=s.queue[i],c=customers[it.type],x=(70+i*42)*sx,y=368*sy;this.add.circle(x,y,7*sx,c.color);this.add.text(x-5*sx,y+9*sy,String(it.patience),{fontFamily:"monospace",fontSize:(6*sx)+"px",color:"#d5cbdc"}).setResolution(2)}}
 popMoney(index,money,type){var sx=this.scale.width/360,sy=this.scale.height/440,col=index%3,row=Math.floor(index/3),x=(72+col*108)*sx,y=(84+row*62)*sy;var txt=this.add.text(x,y,"+¥"+money,{fontFamily:"monospace",fontSize:(9*sx)+"px",color:type==="streamer"?"#ef9bff":"#7be0b0"}).setOrigin(.5).setResolution(2);this.tweens.add({targets:txt,y:y-18*sy,alpha:0,duration:650,onComplete:function(){txt.destroy()}})}
}
new Phaser.Game({type:Phaser.AUTO,parent:"game",backgroundColor:"#09070c",pixelArt:true,antialias:false,roundPixels:true,scale:{mode:Phaser.Scale.RESIZE,width:360,height:440},scene:[Cafe]});
document.getElementById("mainBtn").onclick=function(){var q=s.seats[s.selected];if(!q)buySeat();else if(q.pc&&q.condition<88)repairSeat();else toggleShop("pc")};document.getElementById("shopBtn").onclick=function(){toggleShop("pc")};document.getElementById("facilityBtn").onclick=function(){toggleShop("facility")};document.getElementById("promoBtn").onclick=doPromo;document.getElementById("help").onclick=showHelp;document.getElementById("lang").onclick=function(){s.lang=s.lang==="zh"?"en":"zh";save();renderText()};document.getElementById("reset").onclick=function(){if(confirm(tr("confirm")))newRun()};document.addEventListener("visibilitychange",function(){if(document.hidden)save()});window.addEventListener("beforeunload",save);
if(!s.logs.length)log(s.lang==="zh"?"新店开张。先买座位，再决定走低价客流还是电竞高配。":"New cafe opened. Buy a seat and choose your build.","special");s.target=s.target||targetForDay(s.day);renderText();start();if(!s.seats.some(function(q){return q&&q.pc}))setTimeout(showHelp,220);