"use strict";
function spawnCustomer(){var type=pickCustomer(),c=customers[type];s.queue.push({id:Date.now()+Math.random(),type:type,patience:customerPatience(c)});log(tr("arrive",{who:customerName(type)}));assignQueue()}
function assignQueue(){for(var qi=0;qi<s.queue.length;){var item=s.queue[qi],c=customers[item.type],best=-1,bestTier=99;for(var i=0;i<s.seats.length;i++){var q=s.seats[i];if(!q||!q.pc||q.busy||q.condition<=0)continue;var p=pcBy(q.pc);if(p.tier>=c.tier&&p.tier<bestTier){best=i;bestTier=p.tier}}if(best>=0){s.queue.splice(qi,1);seatCustomer(best,item.type)}else qi++}}
function seatCustomer(index,type){var q=s.seats[index],p=pcBy(q.pc),c=customers[type],money=revenueFor(type,p.tier);q.busy=true;q.customer=type;s.money+=money;s.dailyRevenue+=money;s.served++;s.streak++;if(type==="gamer"||type==="streamer")s.dailyGamers++;if(s.streak%5===0){var tip=12+8*perkCount("loyalty");s.money+=tip;s.dailyRevenue+=tip;log(tr("combo",{n:s.streak,tip:tip}),"special")}var wear=p.wear*wearMul();q.condition=Math.max(0,q.condition-wear);log(tr("served",{who:customerName(type),seat:tr("seat",{n:index+1}),money:money}),"good");render();if(scene)scene.popMoney(index,money,type);var duration=Math.max(650,Math.round(c.duration*durationMul()));setTimeout(function(){if(!s.seats[index])return;s.seats[index].busy=false;s.seats[index].customer=null;maybeBreak(index);assignQueue();render();checkDayEnd()},duration)}
function maybeBreak(index){var q=s.seats[index];if(!q||!q.pc)return;var low=Math.max(0,(35-q.condition)/35),chance=.015+.10*low+.05*s.eventRisk;chance*=Math.max(.25,1-.22*s.facilities.ac);if(Math.random()<chance){var base=55+pcBy(q.pc).tier*18,guard=.40*perkCount("warranty"),loss=Math.round(base*(1-guard));s.money-=loss;q.condition=Math.max(0,q.condition-18);log(tr("break",{seat:tr("seat",{n:index+1}),loss:loss}),"bad")}}
function ageQueue(){for(var i=s.queue.length-1;i>=0;i--){s.queue[i].patience--;if(s.queue[i].patience<=0){var it=s.queue.splice(i,1)[0];s.rep=Math.max(0,s.rep-1);s.streak=0;log(tr("leave",{who:customerName(it.type)}),"bad")}}}
function tick(){if(s.paused||s.over||s.won)return;ageQueue();assignQueue();if(s.arrivals<s.target){s.arrivals++;spawnCustomer()}else checkDayEnd();if(!s.eventDone&&!eventLock&&s.arrivals>=Math.max(3,Math.floor(s.target*.45))&&Math.random()<.16)showRandomEvent();render()}
function start(){clearInterval(timer);timer=null;if(s.over||s.won||s.paused)return;if(s.seats.some(function(q){return q&&q.pc}))timer=setInterval(tick,1250)}
function checkDayEnd(){if(s.arrivals<s.target||s.queue.length)return;if(s.seats.some(function(q){return q&&q.busy}))return;endDay()}
function endDay(){clearInterval(timer);timer=null;s.paused=true;var d=s.day,cost=dailyCost();s.money-=cost;log(tr("end",{day:d,cost:cost}),cost>110?"bad":"");var done=contractProgress()>=s.contract.goal;if(done){var repGain=1+(perkCount("community")>0?1:0);s.money+=s.contract.reward;s.rep+=repGain;log(tr("contractDone",{money:s.contract.reward,rep:repGain}),"good")}else log(tr("contractFail"),"bad");if(bossInfo[d]&&!s.endless){s.money+=bossInfo[d].reward;s.rep+=2;log(tr("bossWin",{money:bossInfo[d].reward}),"special")}
 if(s.money<-250||s.rep<=0){gameOver();return}
 if(d===15&&!s.endless){winRun();return}
 s.day++;prepareDay();save();setTimeout(showPerkDraft,250)}
function prepareDay(){s.arrivals=0;s.served=0;s.queue=[];s.dailyRevenue=0;s.dailyGamers=0;s.promoUsed=false;s.promoBoost=false;s.eventDone=false;s.eventRisk=0;s.target=targetForDay(s.day);s.contract=makeContract(s.day);s.streak=0;s.gamerBias=0;s.paused=true;s.seats.forEach(function(q){if(q){q.busy=false;q.customer=null}});render()}
function perkName(id){var p=perks[id];return s.lang==="zh"?p.nameZh:p.nameEn}
function perkDesc(id){var p=perks[id];return s.lang==="zh"?p.descZh:p.descEn}
function perkDraft(){var pool=Object.keys(perks).filter(function(id){return perkCount(id)<perks[id].max}),pick=[];while(pool.length&&pick.length<3){var idx=Math.floor(Math.random()*pool.length);pick.push(pool.splice(idx,1)[0])}return pick}
function showPerkDraft(){var pick=perkDraft();if(!pick.length){s.paused=false;render();start();return}showModal(tr("modalPerk"),tr("pickPerk"),pick.map(function(id){return{title:perkName(id)+(perks[id].max>1?"  "+(perkCount(id)+1)+"/"+perks[id].max:""),desc:perkDesc(id),className:perks[id].rarity,button:tr("pick"),action:function(){s.perks[id]=perkCount(id)+1;closeModal();s.paused=false;log((s.lang==="zh"?"获得强化：":"Upgrade gained: ")+perkName(id),"special");render();start()}}}))}
function showRandomEvent(){eventLock=true;s.paused=true;var events=["power","team","creator"],id=events[Math.floor(Math.random()*events.length)];if(id==="power")showModal(tr("modalEvent"),tr("eventPowerD"),[{title:tr("eventPowerA"),desc:"",button:tr("pick"),action:function(){s.money-=70;s.eventRisk=-.6;resolveEvent()}},{title:tr("eventPowerB"),desc:"",button:tr("pick"),action:function(){s.eventRisk=.9;resolveEvent()}}],tr("eventPower"));
 if(id==="team")showModal(tr("modalEvent"),tr("eventTeamD"),[{title:tr("eventTeamA"),desc:"",button:tr("pick"),action:function(){s.money-=60;s.rep+=3;s.target+=3;s.gamerBias+=35;resolveEvent()}},{title:tr("eventTeamB"),desc:"",button:tr("pick"),action:function(){s.money+=35;resolveEvent()}}],tr("eventTeam"));
 if(id==="creator")showModal(tr("modalEvent"),tr("eventCreatorD"),[{title:tr("eventCreatorA"),desc:"",button:tr("pick"),action:function(){s.rep+=3;s.streamBias+=5;resolveEvent()}},{title:tr("eventCreatorB"),desc:"",button:tr("pick"),action:function(){s.money+=80;s.rep=Math.max(0,s.rep-1);resolveEvent()}}],tr("eventCreator"))}
function resolveEvent(){s.eventDone=true;eventLock=false;closeModal();s.paused=false;log(tr("eventUsed"),"special");render();start()}
function showModal(kicker,body,choices,title){document.getElementById("modalK").textContent=kicker;document.getElementById("modalT").textContent=title||kicker;document.getElementById("modalB").textContent=body||"";var e=document.getElementById("choices");e.innerHTML=choices.map(function(c,i){return'<div class="choice '+(c.className||"")+'"><h3>'+escapeHtml(c.title||"")+'</h3>'+(c.desc?'<p>'+escapeHtml(c.desc)+'</p>':'')+'<button class="btn primary" data-choice="'+i+'">'+escapeHtml(c.button||tr("pick"))+'</button></div>'}).join("");e.querySelectorAll("[data-choice]").forEach(function(b){b.onclick=function(){choices[Number(b.dataset.choice)].action()}});document.getElementById("overlay").style.display="grid"}
function closeModal(){document.getElementById("overlay").style.display="none"}
function showHelp(){var prev=s.paused;s.paused=true;showModal(tr("help"),tr("helpBody"),[{title:dName(),desc:dDesc(),button:s.lang==="zh"?"继续营业":"Back",action:function(){closeModal();s.paused=prev;start()}}],tr("helpTitle"))}
function gameOver(){s.over=true;s.paused=true;meta.bestDay=Math.max(meta.bestDay,s.day);save();showModal(tr("gameOver"),tr("gameOverD",{day:s.day}),[{title:tr("restart"),desc:dName(),button:tr("restart"),action:function(){newRun()}}],tr("gameOver"))}
function winRun(){s.won=true;s.paused=true;meta.wins++;meta.bestDay=Math.max(meta.bestDay,15);save();showModal(tr("win"),tr("winD"),[{title:tr("endless"),desc:s.lang==="zh"?"保留当前构筑，难度继续上升。":"Keep your build. Difficulty keeps scaling.",button:tr("endless"),action:function(){s.endless=true;s.won=false;s.day++;prepareDay();closeModal();s.paused=false;save();render();start()}},{title:tr("newRun"),desc:s.lang==="zh"?"重新随机街区和构筑。":"Reroll district and build.",button:tr("newRun"),action:function(){newRun()}}],tr("win"))}
function newRun(){var lang=s.lang;localStorage.removeItem(SAVE_KEY);s=baseState();s.lang=lang;shopMode=null;eventLock=false;closeModal();log(s.lang==="zh"?"新店开张。先买座位，再决定走低价客流还是电竞高配。":"New cafe opened. Buy a seat and choose your build.","special");renderText();start();showHelp()}