"use strict";
function renderText(){document.documentElement.lang=s.lang==="zh"?"zh-CN":"en";document.getElementById("title").textContent=tr("title");document.getElementById("sub").textContent=tr("sub");document.getElementById("lang").textContent=tr("lang");["cash","day","rep","cost"].forEach(function(k){document.getElementById(k+"L").textContent=tr(k)});document.getElementById("selL").textContent=tr("sel");document.getElementById("logT").textContent=tr("log");document.getElementById("reset").textContent=tr("reset");document.getElementById("help").textContent=tr("help");document.getElementById("save").textContent=tr("save");render()}
function render(){
 document.getElementById("cash").textContent="¥"+s.money;document.getElementById("day").textContent=s.endless?s.day:(s.day+" / 15");document.getElementById("rep").textContent=s.rep;document.getElementById("cost").textContent="¥"+dailyCost();document.getElementById("district").textContent=dName();
 var nb=nextBossDay();var bi=bossInfo[s.day];document.getElementById("bossLabel").textContent=bossToday()?(tr("bossNow")+" · "+(s.lang==="zh"?bi.titleZh:bi.titleEn)):(nb?tr("nextBoss",{day:nb}):(s.endless?"ENDLESS":""));document.getElementById("bossLabel").className=bossToday()?"bad pulse":"muted";
 var flow=Math.min(s.arrivals,s.target);document.getElementById("flow").textContent=flow+" / "+s.target+(s.queue.length?" · Q"+s.queue.length:"")+" · 🔥"+s.streak;document.getElementById("flowBar").style.width=Math.min(100,Math.round(flow/s.target*100))+"%";document.getElementById("contractText").textContent=tr("contract")+"："+contractLabel();document.getElementById("contractProgress").textContent=contractProgressText();document.getElementById("contractProgress").className=contractProgress()>=s.contract.goal?"good":"muted";
 document.getElementById("record").textContent=tr("record",{day:meta.bestDay,wins:meta.wins});document.getElementById("facilityBtn").textContent=tr("facility");document.getElementById("promoBtn").textContent=s.promoUsed?tr("promoDone"):tr("promo");document.getElementById("promoBtn").disabled=s.promoUsed||s.money<30||s.over||s.won;
 var q=s.seats[s.selected],main=document.getElementById("mainBtn"),shop=document.getElementById("shopBtn"),status=document.getElementById("seatStatus");
 if(!q){document.getElementById("selT").textContent=tr("empty");document.getElementById("desc").textContent=tr("emptyD");status.textContent=tr("emptyStatus");status.className="chip";main.textContent=tr("buySeat",{cost:seatCost()});main.disabled=s.money<seatCost();shop.textContent=tr("shop");shop.disabled=true;if(shopMode==="pc")shopMode=null}
 else if(!q.pc){document.getElementById("selT").textContent=tr("seat",{n:s.selected+1});document.getElementById("desc").textContent=tr("noPc");status.textContent=tr("emptyStatus");status.className="chip";main.textContent=tr("shop");main.disabled=false;shop.textContent=tr("shop");shop.disabled=false}
 else{var p=pcBy(q.pc);document.getElementById("selT").textContent=tr("seat",{n:s.selected+1})+" · "+tr(p.id);document.getElementById("desc").textContent=tr("pcD",{pc:tr(p.id),cond:Math.round(q.condition),tier:p.tier});status.textContent=q.condition<20?tr("brokenStatus"):tr("readyStatus");status.className="chip "+(q.condition<20?"bad":"good");var rc=repairCost(q);main.textContent=q.condition<88?tr("repair",{cost:rc}):tr("shop");main.disabled=q.condition<88?s.money<rc:false;shop.textContent=tr("shop");shop.disabled=false}
 renderShop();renderLog();if(scene)scene.drawCafe();save()
}
function renderLog(){var e=document.getElementById("log");e.innerHTML=s.logs.slice(0,8).map(function(x){return'<div class="log '+x.t+'">'+escapeHtml(x.m)+'</div>'}).join("")||'<div class="log">…</div>'}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})}
function repairCost(q){return Math.max(18,Math.round((100-q.condition)*1.15))}
function buySeat(){var c=seatCost();if(s.money<c)return;s.money-=c;s.seats[s.selected]={pc:null,busy:false,condition:null,customer:null};log(tr("bSeat"),"good");shopMode="pc";render()}
function repairSeat(){var q=s.seats[s.selected];if(!q||!q.pc)return;var c=repairCost(q);if(s.money<c)return;s.money-=c;q.condition=100;log(tr("repaired",{seat:tr("seat",{n:s.selected+1}),cost:c}),"good");render()}
function toggleShop(mode){if(mode==="pc"&&!s.seats[s.selected])return;shopMode=shopMode===mode?null:mode;render()}
function buyPc(id){var p=pcBy(id),q=s.seats[s.selected];if(!q)return;var c=pcPrice(p,q);if(s.money<c)return;s.money-=c;q.pc=id;q.condition=100;q.busy=false;q.customer=null;log(tr("bPc",{seat:tr("seat",{n:s.selected+1}),pc:tr(id)}),"good");shopMode=null;render();start()}
function facilityCost(id,lvl){var base={wifi:[150,270,430],ac:[170,300,480],snack:[130,240,390]};return base[id][lvl]||9999}
function buyFacility(id){var lvl=s.facilities[id]||0;if(lvl>=3)return;var c=facilityCost(id,lvl);if(s.money<c)return;s.money-=c;s.facilities[id]=lvl+1;log((s.lang==="zh"?"设施升级：":"Facility upgraded: ")+tr("facility"+id.charAt(0).toUpperCase()+id.slice(1)),"good");render()}
function renderShop(){var e=document.getElementById("shop");if(!shopMode){e.style.display="none";e.innerHTML="";return}e.style.display="grid";if(shopMode==="pc"){var q=s.seats[s.selected];e.innerHTML=pcs.map(function(p){var c=pcPrice(p,q),cur=q&&q.pc===p.id;return'<div class="cardline"><h3>'+tr(p.id)+' <span class="lvl">T'+p.tier+'</span></h3><p>'+tr(p.id+"D")+'</p><div class="meta"><span>¥'+revenueFor(p.tier===1?"worker":p.tier===2?"gamer":"streamer",p.tier)+'/客</span><span>⚡ '+p.power+'</span><span>磨损 '+p.wear.toFixed(1)+'</span></div><button class="btn '+(cur?"":"primary")+'" data-pc="'+p.id+'" '+((cur||s.money<c)?"disabled":"")+'>'+(cur?tr("equipped"):tr(q&&q.pc?"upgrade":"buy",{cost:c}))+'</button></div>'}).join("");e.querySelectorAll("[data-pc]").forEach(function(b){b.onclick=function(){buyPc(b.dataset.pc)}})}else{
 var fs=[{id:"wifi",name:"facilityWifi",desc:"facilityWifiD"},{id:"ac",name:"facilityAc",desc:"facilityAcD"},{id:"snack",name:"facilitySnack",desc:"facilitySnackD"}];e.innerHTML=fs.map(function(f){var lvl=s.facilities[f.id]||0,c=lvl<3?facilityCost(f.id,lvl):0;return'<div class="cardline"><h3>'+tr(f.name)+' <span class="lvl">'+tr("level",{n:lvl})+'</span></h3><p>'+tr(f.desc)+'</p><button class="btn '+(lvl<3?"primary":"")+'" data-fac="'+f.id+'" '+((lvl>=3||s.money<c)?"disabled":"")+'>'+(lvl>=3?tr("max"):tr("buy",{cost:c}))+'</button></div>'}).join("");e.querySelectorAll("[data-fac]").forEach(function(b){b.onclick=function(){buyFacility(b.dataset.fac)}})}
}
function doPromo(){if(s.promoUsed||s.money<30)return;s.money-=30;s.promoUsed=true;s.promoBoost=true;s.target+=4;log(tr("promoLog"),"special");render()}